stages:
  - test
  - build

variables:
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

unit_tests:
  stage: test
  image: python:3.11-slim
  script:
    - pip install pytest
    - python -m pytest tests/

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - docker build -t $DOCKER_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_TAG