@startuml
left to right direction

actor Пользователь
actor Администратор
actor "Внешние системы" as ExternalSystems

rectangle GlowUp {
  Пользователь -- (Зарегистрироваться/Войти)
  Пользователь -- (Оставить отзыв)
  Пользователь -- ( Поставить оценку товару )
  Пользователь -- (Участвовать в челленджах)
  Пользователь -- (Просматривать рекомендации)
  Пользователь -- (Искать товары на карте)

  Администратор -- (Модерировать отзывы)
  Администратор -- (Управлять челленджами)
  Администратор -- (Анализировать статистику)

  ExternalSystems -- (Синхронизация данных)
  ExternalSystems -- (Обработка платежей)
}


(Зарегистрироваться/Войти) .> (Модерировать отзывы) : extends
(Оставить отзыв) .> (Модерировать отзывы) : extends
(Поставить оценку товару) .> (Синхронизация данных) : extends
(Просматривать рекомендации) .> (Синхронизация данных) : extends
(Искать товары на карте) .> (Синхронизация данных) : extends
(Участвовать в челленджах) .> (Управлять челленджами) : extends
(Обработка платежей) .> (Управлять челленджами) : extends

@enduml