name: Python CI

on:
  workflow_dispatch:
    inputs:
      ShouldRunTests:
        description: 'Запускать тесты?'
        type: boolean
        default: true
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check test flag
        if: ${{ !inputs.ShouldRunTests && github.event_name == 'workflow_dispatch' }}
        run: |
          echo "⚠️ Тесты пропущены по требованию (ShouldRunTests=false)"
          echo "Это не ошибка, просто тесты отключены явно"
          
      - name: Run tests
        if: ${{ inputs.ShouldRunTests || github.event_name != 'workflow_dispatch' }}
        run: pytest -v tests/

      - name: "🍿 Выполняем важный скрипт"
        run: |
          echo "📜 Инструкция: Как открыть банку кукурузы:"
          echo "1. Возьмите банку и консервный нож"
          echo "2. Подденьте крышку ножом"
          echo "3. Прокрутите нож по окружности банки"
          echo "4. 🎉 Поздравляем! Кукуруза освобождена!"
          echo "Текущая дата: $(date)"